name: CI Build Step - Deploy Image to ECR

on: 
  workflow_dispatch:
    inputs:
      command:
        description: "The command to run"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 624626124579.dkr.ecr.us-east-1.amazonaws.com                   
  ECR_REPOSITORY: examplecontextimages
  TF_VERSION: '1.9.3'
  TG_VERSION: '0.63.6'
  TG_DIR: 'live/aws/_initializations/example-context'
  TG_LOCAL_PATH: 'deploy'

jobs:
  deploy:
    name: Build, Test, & Deploy
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout cloud-deployment
        uses: actions/checkout@v4
        with:
          repository: dashg-enterprises/cloud-deployment
          token: ${{ secrets.CLOUD_DEPLOYMENT_PAT }}
          path: ${{ env.TG_LOCAL_PATH }}
          sparse-checkout: |
            ${{ env.TG_DIR }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        # uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Ensure Bounded Context is initialized
        uses: gruntwork-io/terragrunt-action@v2
        env:
          INPUT_PRE_EXEC_1: |
            git config --global url."https://user:${{secrets.DASHG_CLOUD_PLATFORM_PAT}}@github.com/dashg-enterprises/cloud-platform".insteadOf "https://github.com/dashg-enterprises/cloud-platform"
          INPUT_PRE_EXEC_2: |
            git config --global url."https://user:${{secrets.CLOUD_DEPLOYMENT_PAT}}@github.com".insteadOf "https://github.com"
          INPUT_PRE_EXEC_3: |
            git config --global --list
        with:
          TF_VERSION: ${{ env.TF_VERSION }}
          TG_VERSION: ${{ env.TG_VERSION }}
          tg_dir: ${{ env.TG_LOCAL_PATH }}/${{ env.TG_DIR }}
          tg_command: '${{ inputs.command }} --terragrunt-source ../../../../..//iac/initialization'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }} 
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT