name: CI Basic Merge Step - PR and Merge to cloud-deployment

on: workflow_dispatch

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 624626124579.dkr.ecr.us-east-1.amazonaws.com                   
  ECR_REPOSITORY: examplecontextimages
  TF_VERSION: '1.9.3'
  TG_VERSION: '0.63.6'
  TG_PATH: 'deploy'
  TG_DIR: 'live/aws/_initializations/example-context'
  TG_APP_DIR: 'live/aws/dev/applications/example-context'

jobs:
  deploy:
    name: Merge Build
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout cloud-deployment
        uses: actions/checkout@v4
        with:
          repository: dashg-enterprises/cloud-deployment
          token: ${{ secrets.CLOUD_DEPLOYMENT_PAT }}
          path: ${{ env.TG_PATH }}

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1' # The Go version to download (if necessary) and use.

      - name: Get hcledit
        run: |
          git clone https://github.com/minamijoyo/hcledit
          cd hcledit/
          make install
          hcledit version

      - name: Change directory into deployment repo
        run: |
          cd '${{ env.TG_PATH }}/${{ env.TG_APP_DIR }}'
          cat terragrunt.hcl
          echo 'first try'
          cat terragrunt.hcl | hcledit attribute set inputs.application_image '"${{ github.sha }}"'
          echo 'another try'
          cat terragrunt.hcl | hcledit attribute set locals.application_image '"${{ github.sha }}"'
          echo 'last print'
          cat terragrunt.hcl

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: "build/${{ env.ECR_REPOSITORY }}-${{ github.sha }}"
          commit-message: "Update build for ${{ github.sha }}"
          token: ${{ secrets.CLOUD_DEPLOYMENT_PAT }}
          path: ${{ env.TG_PATH }}